name: test

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/test.yml"
      - "lib/*s"
      - "proto/**"
      - "src/**"
      - "tests/**"
      - "Cargo.lock"
      - "Cargo.toml"
      - "docker-compose.yml"
      - "rust-toolchain"

  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "lib/*s"
      - "proto/**"
      - "src/**"
      - "tests/**"
      - "Cargo.lock"
      - "Cargo.toml"
      - "docker-compose.yml"
      - "rust-toolchain"

env:
  AWS_ACCESS_KEY_ID: fake-aws-key
  AWS_SECRET_ACCESS_KEY: fake-aws-key
  RUST_BACKTRACE: full
  TARGET: x86_64-unknown-linux-gnu
  TEST_LOG: debug
  USE_CONTAINER: none

jobs:
  behavior:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test-behavior

  integration-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test-integration-aws

  integration-clickhouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test-integration-clickhouse

  integration-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test-integration-docker

  integration-elasticsearch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test-integration-elasticsearch

  integration-gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test-integration-gcp

  integration-influxdb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test-integration-influxdb

  integration-kafka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test-integration-kafka

  integration-loki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test-integration-loki

  integration-pulsar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test-integration-pulsar

  integration-splunk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test-integration-splunk

  integration-kubernetes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes:
          - v1.18.2
          - v1.17.5
          - v1.16.9
          - v1.15.11
          - v1.14.10
    steps:
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v1.0.2
        with:
          minikube version: 'v1.9.2'
          kubernetes version: '${{ matrix.kubernetes }}'
          github token: '${{ secrets.GITHUB_TOKEN }}'
      - uses: actions/checkout@v1
      - run: make test-integration-kubernetes

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make slim-builds
      - run: make test-unit
